image: docker:stable

stages:
  - build
  - test
  - release
  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:gitlab-ci-dev
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:gitlab-ci

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - export FRONTEND_IMAGE_TAG=$CONTAINER_TEST_IMAGE

build:
  stage: build
  script:
    - docker-compose -f docker_extra/prod.yml build
    - docker push $CONTAINER_TEST_IMAGE

tests:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker-compose -f docker_extra/prod.yml up -d
    - export FRONTEND_ADDR="http://frontend:80"; export GUI=false; docker-compose -f docker_extra/test.yml up --build --exit-code-from frontend_test
    - docker-compose -f docker_extra/prod.yml down
  # coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy:
  stage: deploy
  script:
    - curl --fail -XPOST "$DEPLOY_WEBHOOK"
  only:
    - master
