# Compose used for development
# This file is needed because volumes are appended on override.
# So prod would also have dev's volumes, what should not happen.

version: '3.5'

services:

  frontend:
    build:
      context: ${FRONTEND_PATH:-.}
    image: agoradigital/frontend-dev
    container_name: frontend_dev
    tty: true
    volumes:
      - ${FRONTEND_PATH:-.}/src:/app/src
      - ${FRONTEND_PATH:-.}/tests:/app/tests
      - ${FRONTEND_PATH:-.}/public:/app/public
    ports:
      - "3000:8080"

networks:
  default:
    name: agoradigital
