# Compose used for development
# This file is needed because volumes are appended on override.
# So prod would also have dev's volumes, what should not happen.

version: '3'

services:

  frontend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: agoradigital/frontend
    container_name: frontend
    ports:
      - "9001:80"
