# Compose used for development
# This file is needed because volumes are appended on override.
# So prod would also have dev's volumes, what should not happen.

version: '3.2'

services:

  frontend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    # image: agoradigital/frontend
    image: registry.gitlab.com/analytics-ufcg/front:gitlab-ci-dev
    container_name: frontend
    ports:
      - "9001:80"
